version: '3.8'

services:
  streamlit:
    image: eduszabolcsfule/streamlit-app:latest
    container_name: streamlit-app
    ports:
      - "8501:8501"
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring

  graylog:
    image: graylog/graylog:5.0
    container_name: graylog
    environment:
      GRAYLOG_ROOT_PASSWORD_SHA2: 7c222fb2927d828af22f592134e8932480637c0d
      GRAYLOG_HTTP_EXTERNAL_URI: http://127.0.0.1:9000/
    ports:
      - "9000:9000"
      - "12201:12201/udp"
    networks:
      - monitoring

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-6.4-latest
    container_name: zabbix-server
    ports:
      - "10051:10051"
    environment:
      DB_SERVER_HOST: zabbix-db
    networks:
      - monitoring

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-6.4-latest
    container_name: zabbix-web
    ports:
      - "8080:8080"
    environment:
      DB_SERVER_HOST: zabbix-db
    networks:
      - monitoring

  zabbix-db:
    image: postgres:latest
    container_name: zabbix-db
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
